# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e858e31c40c33d27607a475681adb5586475350836433908da402d976d4e744e82d117d21d460f0d8200ada166aa66425586e1d58667de695aa39db9b78aaf2b

test:
  secret_key_base: b99af914bf3daf7204c5f910bd051ae86cb9b8867b36d90931b4214e506e3102258a37940e16492e06c348df387f82e603f72db1d2cbd262b83b1f5a165ee48a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
